<!DOCTYPE html>
<html dir="ltr" lang="en-gb">

<!-- Mirrored from forum.abinit.org/viewtopic.php?f=12&t=4287&view=print by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 20 Sep 2024 16:50:55 GMT -->
<!-- Added by HTTrack --><meta http-equiv="content-type" content="text/html;charset=UTF-8" /><!-- /Added by HTTrack -->
<head>
<meta charset="utf-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="robots" content="noindex" />

<title>ABINIT Discussion Forums &bull; Temperature-dependency and temperature_final.py script</title>

<link href="styles/flat-style/theme/print.css" rel="stylesheet">
<link href="styles/flat-style/theme/bidi.css" rel="stylesheet">
</head>
<body id="phpbb" class="ltr">
<div id="wrap" class="wrap">
	<a id="top" class="top-anchor" accesskey="t"></a>

	<div id="page-header">
		<h1>ABINIT Discussion Forums</h1>
		<p>The meeting place for ABINIT users and developers<br /><a href="index.html">https://forum.abinit.org/</a></p>

		<h2>Temperature-dependency and temperature_final.py script</h2>
		<p><a href="viewtopic3275.html?f=12&amp;t=4287">https://forum.abinit.org/viewtopic.php?f=12&amp;t=4287</a></p>
	</div>

	<div id="page-body" class="page-body">
		<div class="page-number">Page <strong>1</strong> of <strong>1</strong></div>
					<div class="post">
				<h3>Temperature-dependency and temperature_final.py script</h3>
				<div class="date">Posted: <strong>Wed Jan 01, 2020 10:31 am</strong></div>
				<div class="author">by <strong>MasoudMS</strong></div>
				<div class="content">Hi ABINIT friends,<br>
I am trying the temperature-dependency of the bandgap of the carbon in the "tdeps_1" tutorial. When using the default "ngkpt 2 2 2", the temperature_final.py script works well but by changing the "ngkpt 2 2 2" to "4 4 4" the script has an error. Indeed, with "2 2 2" value there are 8 kpts and with "4 4 4" value there are 36 kpts and when running the script the following error arises:<br>
"Enter the name of the unperturbed EIG.nc file at Gamma<br>
Traceback (most recent call last):<br>
  File "./temperature_final.py", line 464, in &lt;module&gt;<br>
    sys.exit(main())<br>
  File "./temperature_final.py", line 223, in main<br>
    if N.allclose(eig0.EIG[ispin,ikpt,iband+1], eig0.EIG[ispin,ikpt,iband]):<br>
IndexError: index 36 is out of bounds for axis 1 with size 36"<br>
<br>
Is it a bug? How do I solve this problem?<br>
<br>
Thanks</div>
			</div>
			<hr />
			</div>

	<div id="page-footer" class="page-footer">
		<div class="page-number">All times are <span title="Europe/Brussels">UTC+02:00</span><br />Page <strong>1</strong> of <strong>1</strong></div>
			<div class="copyright">
				<p>Powered by <a href="https://www.phpbb.com/">phpBB</a>&reg; Forum Software &copy; phpBB Limited
				</p>
							</div>
	</div>
</div>

</body>

<!-- Mirrored from forum.abinit.org/viewtopic.php?f=12&t=4287&view=print by HTTrack Website Copier/3.x [XR&CO'2014], Fri, 20 Sep 2024 16:50:55 GMT -->
</html>
